[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "website", "webapp", "wasm", "webassembly"]
license = "MIT"
name = "webapp-frontend"
readme = "README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "0.1.0"

[badges]
circle-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }
codecov = { repository = "saschagrunert/webapp.rs", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "app"
path = "src/main.rs"

[build-dependencies]
failure = "0.1.5"
sass-rs = "0.2.1"
url = "1.7.2"
webapp = { path = ".." }

[dependencies]
failure = "0.1.5"
log = "0.4.6"
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
webapp = { path = ".." }
yew = { git = "https://github.com/DenisKolodin/yew", features = ["cbor"] }
yew-router = { git = "https://github.com/saschagrunert/yew-router" }
