[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "website", "webapp", "wasm", "webassembly"]
license = "MIT"
name = "webapp"
readme = "README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "0.3.0"

[badges]
circle-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }
codecov = { repository = "saschagrunert/webapp.rs", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
diesel = { version = "1.3.3", optional = true }
failure = "0.1.2"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4.7"

[features]
backend = ["diesel"]

[workspace]
members = [
    "backend",
    "frontend",
]
