[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "website", "webapp", "wasm", "webassembly"]
license = "MIT"
name = "webapp"
readme = "README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "0.3.0"

[badges]
travis-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }

[[bin]]
name = "app"
path = "src/frontend/main.rs"
required-features = ["frontend"]

[[bin]]
name = "backend"
path = "src/backend/main.rs"

[build-dependencies]
capnpc = "0.8.9"
failure = "0.1.1"
sass-rs = "0.2.1"
serde = "1.0.70"
serde_derive = "1.0.70"
toml = "0.4.6"

[dev-dependencies]
capnp = "0.8.17"
futures = "0.1.22"
lazy_static = "1.0.1"
toml = "0.4.6"
tungstenite = { version = "0.5.4", default-features = false }
url = "1.7.1"

[dependencies]
actix = { version = "0.5.8", optional = true }
actix-web = { version = "0.6.14", optional = true, features = ["alpn"] }
capnp = "0.8.17"
diesel = { version = "1.3.2", optional = true, features = ["r2d2", "postgres"] }
env_logger = { version = "0.5.10", optional = true }
failure = "0.1.1"
futures = { version = "0.1.22", optional = true }
jsonwebtoken = { version = "4.0.1", optional = true }
lazy_static = "1.0.1"
log = { version = "0.4.3", optional = true }
openssl = { version = "0.10.10", optional = true }
num_cpus = { version = "1.8.0", optional = true }
r2d2 = { version = "0.8.2", optional = true }
serde = "1.0.70"
serde_derive = "1.0.70"
stdweb = { version = "0.4.7", optional = true }
time = { version = "0.1.40", optional = true }
toml = { version = "0.4.6", optional = true }
uuid = { version = "0.6.5", optional = true, features = ["v4"] }
yew = { git = "https://github.com/DenisKolodin/yew", optional = true }

[features]
default = [
    "actix",
    "actix-web",
    "diesel",
    "env_logger",
    "futures",
    "jsonwebtoken",
    "log",
    "num_cpus",
    "openssl",
    "r2d2",
    "time",
    "toml",
    "uuid"
]
frontend = [
    "stdweb",
    "yew"
]
