[package]
name = "webapp"
version = "0.1.0"
license = "MIT"
readme = "README.md"
keywords = ["web", "app", "website", "webapp"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/webapp.rs"
homepage = "https://github.com/saschagrunert/webapp.rs"
documentation = "https://docs.rs/webapp"
description = "A web application completely written in Rust"
categories = ["web-programming"]

[badges]
travis-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }
appveyor = { repository = "saschagrunert/webapp.rs", branch = "master", service = "github" }

[[bin]]
name = "frontend"
path = "src/frontend/main.rs"
required-features = ["frontend"]

[[bin]]
name = "backend"
path = "src/backend/main.rs"
required-features = ["backend"]

[dependencies]
failure = "0.1.1"
env_logger = { version = "0.5.10", optional = true }
log = { version = "0.4.2", optional = true }
mowl = { version = "1.3.0", optional = true }
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
stdweb = { version = "0.4.6", optional = true }
tungstenite = { version = "0.5.3", optional = true }
yew = { version = "0.4.0", optional = true }

[features]
frontend = [
    "stdweb",
    "yew",
]
backend = [
    "env_logger",
    "log",
    "mowl",
    "tungstenite",
]
