[server]
url = "http://127.0.0.1:30080"
cert = "tls/cert.pem"
key = "tls/key.pem"
redirect-from = [
    "http://127.0.0.1:30081",
    "https://127.0.0.1:30082",
]

[log]
actix-web = "debug"
webapp = "trace"

[postgres]
host = "127.0.0.1"
username = "username"
password = "password"
database = "database"
