[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "webapp", "wasm", "webassembly"]
license = "MIT"
name = "webapp-backend"
readme = "../README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "1.0.0"
edition = "2018"

[badges]
circle-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }
codecov = { repository = "saschagrunert/webapp.rs", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "backend"
path = "src/main.rs"

[dev-dependencies]
actix-http-test = "0.2.4"
actix-http = "0.2.8"
lazy_static = "1.3.0"
reqwest = "0.9.19"

[dependencies]
actix = "0.8.3"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-web = { version = "1.0.5", features = ["ssl"] }
bytes = "0.4.12"
clap = { version = "2.33.0", features = ["yaml"] }
diesel = { version = "1.4.2", features = ["r2d2", "postgres"] }
env_logger = "0.6.2"
failure = "0.1.5"
futures = "0.1.28"
jsonwebtoken = "6.0.1"
log = "0.4.8"
num_cpus = "1.10.1"
openssl = "0.10.24"
r2d2 = "0.8.5"
serde = { version = "1.0.99", features = ["derive"]}
serde_cbor = "0.10.1"
time = "0.1.42"
url = "2.1.0"
uuid = { version = "0.7.4", features = ["v4"] }
webapp = { version = "1.0.0", path = "..", features = ["backend"] }
