[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["web-programming"]
description = "A web application completely written in Rust"
documentation = "https://docs.rs/webapp"
homepage = "https://github.com/saschagrunert/webapp.rs"
keywords = ["web", "app", "website", "webapp", "wasm", "webassembly"]
license = "MIT"
name = "webapp-backend"
readme = "README.md"
repository = "https://github.com/saschagrunert/webapp.rs"
version = "0.1.0"
edition = "2018"

[badges]
circle-ci = { repository = "saschagrunert/webapp.rs", branch = "master" }
codecov = { repository = "saschagrunert/webapp.rs", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "backend"
path = "src/main.rs"

[dev-dependencies]
lazy_static = "1.2.0"
reqwest = "0.9.16"

[dependencies]
actix = "0.7.9"
actix-web = { version = "0.7.19", features = ["alpn"] }
bytes = "0.4.12"
clap = { version = "2.33.0", features = ["yaml"] }
diesel = { version = "1.4.2", features = ["r2d2", "postgres"] }
env_logger = "0.6.1"
failure = "0.1.5"
futures = "0.1.26"
jsonwebtoken = "5.0.1"
log = "0.4.6"
num_cpus = "1.10.0"
openssl = "0.10.16"
r2d2 = "0.8.4"
serde = "1.0.90"
serde_cbor = "0.9.0"
serde_derive = "1.0.90"
time = "0.1.42"
url = "1.7.2"
uuid = { version = "0.7.4", features = ["v4"] }
webapp = { path = "..", features = ["backend"] }
